### ISSUE TITLE
RedirectHandler maintains `max_redirect` state across requests

### ISSUE THREAD

**Issue by vpotter** [microsoft/kiota-http-python#246]
When using RedirectHandler for multiple requests without specifying custom options, we encounter an issue where the `max_redirect` counter is shared across all requests handled by a single RedirectHandler instance. This is problematic when downloading drive items using the [Microsoft Graph API](https://learn.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=python#response), which respond with a `302 Found` redirect to a preauthenticated download URL.

After 5 successive downloads, the handler raises `Too many redirects` exception due to the shared counter reaching its default limit, effectively preventing further downloads.

**Comment by baywet** [comment]
Hi @vpotter 
Thanks for your interest in kiota and for reporting this.
My Python is not great but to me it looks like:
- The request history should not be a field on the middleware handler, but rather a variable
- The decrement should not be made on the options field directly, but rather on a copied variable
- The retry handler might also be having the same issue.

https://github.com/microsoft/kiota-http-python/blob/main/kiota_http/middleware/redirect_handler.py#L36

Is this something you'd be willing to submit a pull request for?

**Comment by snorrea** [comment]
While we wait for a resolution, are there any workarounds for this issue, in particular when using the `msgraph` SDK? We are blocked by this when doing file downloads for an archiving system.

**Comment by baywet** [comment]
not that I know off besides disabling the handler all together which is not going to workaround your issue here.
But a PR was started, see #258

**Comment by Nintorac** [comment]
@snorrea there is a workaround [here](https://github.com/microsoftgraph/msgraph-sdk-python/issues/504)
