### ISSUE TITLE
Retry handler decreases the option's retry attempts

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-http-python#281]
Follow up to #258
(we should really inspect all middleware handlers)

This means if multiple requests need to retry within the lifetime of the client/request adapter/handler, the first requests will retry successfully but the following ones won't. (same issue as redirect handler)

https://github.com/microsoft/kiota-http-python/blob/f64b0f8d478fae3da5edf7833041c92f9d91fc4c/kiota_http/middleware/retry_handler.py#L97

**Comment by sebastienlevert** [comment]
@shemogumbe is this closed?

**Comment by baywet** [comment]
no this isn't and still needs work
