### ISSUE TITLE
Error importing GraphServiceClient

### ISSUE THREAD

**Issue by DevObs1** [microsoft/kiota-http-python#384]
**Environment**

- Python Version: 3.7.4
- kiota-http version: 0.6.3
- OS: W10 x64

**Stack trace (if available)**
![image](https://github.com/microsoft/kiota-http-python/assets/31596745/bd7f34f8-cd8c-4d45-8363-43784570e67c)
![image](https://github.com/microsoft/kiota-http-python/assets/31596745/de00a2be-c823-436f-a76d-1a515d04868b)

**Describe the bug**
**from msgraph import GraphServiceClient** does not work. This gives me a syntax error.

**To Reproduce**

1. install msgraph-sdk: pip install msgraph-sdk (microsoft-kiota-http is included in it)
2. Create a python file with the import below : from msgraph import GraphServiceClient
3. Run the script

**Expected behavior**
That there is no error when importing

**Screenshots**

**Additional context**

**Comment by baywet** [comment]
Hi @DevObs1 
Thanks for using the Microsoft graph SDK and for reaching out . 
This is a rather old version of a dependency. Have you tried upgrading to the latest version of the SDK and of kiota HTTP?

**Comment by DevObs1** [comment]
Hi @baywet,
Thank you for your answer.

I forced the msgraph-sdk upgrade.
`pip install --upgrade --force-reinstall --no-cache-dir msgraph-sdk`

Also the microsoft-kiota_http upgrade
`pip install --upgrade --force-reinstall --no-cache-dir microsoft-kiota-http`

pip show msgraph-sdk gives me:
`Version: 1.0.0a13`

and pip show microsoft-kiota_http gives me:
`Version: 0.6.3`

I saw that the latest version of microsoft-kiota_http was 1.3.2.
Why is it that even if I force the upgrade, it doesn't do it?

**Comment by baywet** [comment]
are you using python <3.8 by any chance? have you tried upgrading to 3.12?

**Comment by DevObs1** [comment]
I was on 3.7.4 and upgraded to 3.12 and it works.
Maybe indicate it in the README to avoid this for other people? :)

Thank you for your help and your responsiveness!

**Comment by baywet** [comment]
Isn't this enough?
![image](https://github.com/microsoft/kiota-http-python/assets/7905502/e9c5cfae-9bd3-405b-b092-bafc3e4231f7)
